server:
  port: 9082
  servlet:
    context-path: /hotelService/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotelservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: HOTEL-SERVICE
    
eureka:
  instance:
    ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka